/**
 * Type definitions for graph-schema.json — the semantic dependency graph
 * artifact generated by /code-atlas:map and /code-atlas:update (v2.0).
 *
 * graph-schema.json stores annotated nodes (modules/files with semantic
 * metadata) and edges (dependencies with type, strength, directionality,
 * and impact) for querying via /code-atlas:query.
 */

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

export interface GraphSchemaHeader {
  /** Schema format version. Current: 2 */
  schema_version: 2;
  /** Code Atlas plugin version that wrote the file, e.g. "2.0.0" */
  plugin_version: string;
  /** ISO 8601 UTC timestamp when this file was generated */
  generated_at: string;
  /** Short git commit SHA at time of generation, or empty string if unavailable */
  baseline_commit: string;
  /** Root directory that was scanned, e.g. "." */
  scan_root: string;
}

// ---------------------------------------------------------------------------
// Node
// ---------------------------------------------------------------------------

/**
 * Logical role of a module or file inferred from directory structure and
 * importer patterns.
 */
export type NodeRole =
  | "entry_point"
  | "core_module"
  | "utility"
  | "config"
  | "middleware"
  | "model"
  | "public_api"
  | "route_definition"
  | "internal";

/**
 * Blast-radius criticality based on importer counts.
 * - critical : importer_count >= 10
 * - high     : importer_count >= 5
 * - medium   : importer_count >= 2
 * - low      : importer_count < 2
 */
export type NodeCriticality = "critical" | "high" | "medium" | "low";

/**
 * Inferred change frequency / maturity of the module.
 * - stable      : no experimental/beta/dev directory markers, low churn
 * - evolving    : recent high churn or in-progress refactors
 * - experimental: lives under experimental/, beta/, or dev/ directory
 */
export type NodeStability = "stable" | "evolving" | "experimental";

/**
 * Presence of colocated test files.
 * - well_tested : both *.test.ts and *.spec.ts siblings found
 * - partial     : one sibling test file found
 * - untested    : no colocated test files
 */
export type NodeTestCoverage = "well_tested" | "partial" | "untested";

/**
 * Discriminated union describing whether a graph node represents a logical
 * module (directory of files) or a single standalone file.
 */
export type NodeType = "module" | "file";

/**
 * A node in the semantic dependency graph.
 *
 * When `type` is `"module"` the node represents a logical subsystem
 * (e.g. `src/auth/`) and `files` lists its constituent source files.
 *
 * When `type` is `"file"` the node is a single source file and `files`
 * is absent (the path itself is the file).
 */
export interface GraphNode {
  /** `"module"` for a directory-level subsystem; `"file"` for a single file */
  type: NodeType;
  /**
   * Constituent source files within a module node.
   * Present only when `type === "module"`.
   */
  files?: string[];
  /** Inferred semantic role within the codebase */
  role: NodeRole;
  /** Blast-radius criticality derived from importer counts */
  criticality: NodeCriticality;
  /** Inferred change frequency and maturity */
  stability: NodeStability;
  /** Presence of colocated test files */
  test_coverage: NodeTestCoverage;
  /** One-line human-readable description of the module/file purpose */
  description: string;
}

/**
 * Index of all graph nodes keyed by module/file path
 * (e.g. `"src/auth"`, `"src/utils/logger.ts"`).
 */
export type GraphNodes = Record<string, GraphNode>;

// ---------------------------------------------------------------------------
// Edge
// ---------------------------------------------------------------------------

/**
 * Nature of the dependency between two nodes.
 * - direct_import  : static ES/CommonJS import statement
 * - dynamic_import : import() expression or require() at runtime
 * - inheritance    : class extends / implements relationship
 * - composition    : one class/module constructs or holds an instance of another
 * - configuration  : dependency on a config/settings module at startup
 * - sideeffect     : import solely for its side effects (e.g. polyfills)
 */
export type EdgeType =
  | "direct_import"
  | "dynamic_import"
  | "inheritance"
  | "composition"
  | "configuration"
  | "sideeffect";

/**
 * How essential the edge is to the source module's function.
 * - core     : removing this edge would break core functionality
 * - utility  : convenient helper; removal is painful but survivable
 * - optional : conditional or feature-flagged; not always exercised
 */
export type EdgeStrength = "core" | "utility" | "optional";

/**
 * Structural relationship between source and target.
 * - required    : source strictly depends on target (one-way)
 * - circular    : source and target mutually depend on each other
 * - conditional : source only sometimes depends on target
 */
export type EdgeDirectionality = "required" | "circular" | "conditional";

/**
 * Predicted consequence if the source node changes its public API or is
 * removed. Empty string means no special impact annotation.
 * - breaking_change_risk    : target's API shift would likely break source
 * - ripple_effect_magnitude : source change propagates to many downstream nodes
 */
export type EdgeImpact = "breaking_change_risk" | "ripple_effect_magnitude" | "";

/**
 * A directed dependency edge from `source` to `target`.
 */
export interface GraphEdge {
  /** Path of the importing module/file (the dependent) */
  source: string;
  /** Path of the imported module/file (the dependency) */
  target: string;
  /** Nature of the import relationship */
  type: EdgeType;
  /** Essentiality of the dependency */
  strength: EdgeStrength;
  /** Structural flow of the relationship */
  directionality: EdgeDirectionality;
  /**
   * Predicted impact if source or target changes.
   * Empty string when no specific impact annotation applies.
   */
  impact: EdgeImpact;
}

// ---------------------------------------------------------------------------
// Metadata summary
// ---------------------------------------------------------------------------

export interface GraphMetadata {
  /** Total number of nodes in the graph */
  total_nodes: number;
  /** Total number of edges in the graph */
  total_edges: number;
  /** Number of key modules that were analyzed to build the graph */
  key_modules_analyzed: number;
  /** Number of circular dependency pairs detected */
  circular_dependency_count: number;
}

// ---------------------------------------------------------------------------
// Root document
// ---------------------------------------------------------------------------

/**
 * Root structure of `.code-atlas/graph-schema.json`.
 *
 * Generated by `/code-atlas:map` and `/code-atlas:update`.
 * Consumed (read-only) by the `/code-atlas:query` skill.
 */
export interface GraphSchema {
  _header: GraphSchemaHeader;
  /**
   * Nodes keyed by module/file path.
   * Only key modules (from atlas.json key_files + high_traffic) and their
   * immediate in-key-set dependencies/dependents are included.
   */
  nodes: GraphNodes;
  /**
   * Directed dependency edges between nodes in this graph.
   * Both source and target paths reference keys present in `nodes`.
   */
  edges: GraphEdge[];
  /** Aggregate counts for quick overview */
  metadata: GraphMetadata;
}
